### ISSUE TITLE
zoom in/out of screen

### ISSUE THREAD

**Issue by canyouseemyscreen** [ihernandez812/StudyHelper#19]
the screenshot is huge so it would be easier to position the structure to zoom in and out.

**Comment by ihernandez812** [comment]
Rather than giving you the ability to zoom in an out of images. Would it be fine if I allow you to scale the images up and
down when adding/editing a body part? 
Example of what it would look like using the image you sent Megan:
<img width="1363" alt="Screenshot 2024-11-12 at 9 27 48 PM" src="https://github.com/user-attachments/assets/c2f75161-d8a0-46aa-857d-a6f4c9a32959">

Only thing is the font of the tags would scale up and down. I can either change it automatically or have a font size chooser for each body part. 

When taking a body part test or practical exam the scale you chose would persist.

**Comment by canyouseemyscreen** [comment]
a font size scale would be more beneficial bc if it were to do it automatically - i dont know if it would be too big/small.
